apiVersion: v1
kind: ConfigMap

metadata:
  name: prometheus-alert-rules

data:
  alert.rules.yml: |
    groups:
      - name: guardianstack-alerts

        rules:

          - alert: FlaskAppDown

            expr: up{job="flask-app"} == 0

            for: 10s

            labels:
              severity: critical

            annotations:
              summary: "Flask app is DOWN"
