apiVersion: apps/v1
kind: Deployment

metadata:
  name: webhook

spec:
  replicas: 1

  selector:
    matchLabels:
      app: webhook

  template:
    metadata:
      labels:
        app: webhook

    spec:
      containers:
      - name: webhook

        image: guardianstack-webhook:v2

        imagePullPolicy: Never
        
        env:
        - name: STORAGE_BACKEND
          value: "local"

        ports:
        - containerPort: 5001
